name: Docker Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: prueba3
          file: ./prueba3/Dockerfile
          push: false
          tags: mi-nginx
      
      - name: Change working directory
        run: cd prueba3
      - name: Deploy with Dockers Compose
        run: docker-compose up -d
